name: BukkitProtect
main: io.github.elitejynx.BukkitProtect.BukkitProtect
version: A-1.7
description: BukkitProtect, protecting your worlds since it was made!
authors: [EliteJynx]
permissions:
  BukkitProtect.Protection.*:
    description: Gives access to all protection permissions
    children:
      BukkitProtect.Protection.MakeProtections: true
      BukkitProtect.Protection.SelectOthers: true
      BukkitProtect.Protection.RemoveOthers: true
      BukkitProtect.Protection.EditOthers: true
  BukkitProtect.Protection.MakeProtections:
    description: Gives player access to selecting others regions
    default: true
  BukkitProtect.Protection.SelectOthers:
    description: Gives player access to selecting others regions
    default: op
  BukkitProtect.Protection.RemoveOthers:
    description: Allows player to remove others regions
    default: op
  BukkitProtect.Protection.EditOthers:
    description: Allows player to edit others regions
    default: op
  BukkitProtect.Commands.*:
    description: Gives access to all command permissions
    children:
      BukkitProtect.Commands.GiveRod: true
      BukkitProtect.Commands.Tag: true
      BukkitProtect.Commands.AdminLand: true
      BukkitProtect.Commands.GetLand: true
      BukkitProtect.Commands.Users: true
      BukkitProtect.Commands.Transfer: true
      BukkitProtect.Commands.Accept: true
      BukkitProtect.Commands.RemoveProtections: true
      BukkitProtect.Commands.Stuck: true
  BukkitProtect.Commands.GiveRod:
    description: Give yourself a Rod of the Admin
    default: op
  BukkitProtect.Commands.Tag:
    description: Allows players to use the add/removeTag command
    default: op
  BukkitProtect.Commands.AdminLand:
    description: Allows players to use the land commands
    default: op
  BukkitProtect.Commands.GetLand:
    description: Allows players to use the getland command on their own land
    default: true
  BukkitProtect.Commands.Users:
    description: Allow players to use the add/remove/getUsers command
    default: true
  BukkitProtect.Commands.Transfer:
    description: Allows players to use the Transfer command
    default: true
  BukkitProtect.Commands.Accept:
    description: Allows players to use the accept command
    default: true
  BukkitProtect.Commands.RemoveProtections:
    description: Allows players to use the remove(all)protection(s) commands
    default: true
  BukkitProtect.Commands.Stuck:
    description: Allows players to use the Stuck command
    default: true
commands:
  GiveRod:
    description: Give yourself a Rod of the Admin
    usage: /<command> [player]
  AddUsers:
    description: Add a player to the selected protection
    usage: /<command> [player] [type]
  RemoveUsers:
    description: Remove a player from the selected protection
    usage: /<command> [player] [type]
  GetUsers:
    description: Gets the users in the selected protection
    usage: /<command>
  SetOwner:
    description: Set a player as the owner of the selected protection
    usage: /<command> [player]
  Transfer:
    description: Give a player the selected protection
    usage: /<command> [player]
  Accept:
    description: Accept the latest request
    usage: /<command>
  RemoveProtection:
    description: Remove the selected protection
    usage: /<command>
  RemoveAllProtections:
    description: Remove all your protection
    usage: /<command> [player]
  AddTag:
    description: Add a tag to the selected protection
    usage: /<command> [Tag] [Value]
  RemoveTag:
    description: Remove a tag from the selected protection
    usage: /<command> [Tag]
  GetTags:
    description: Get tags from the selected protection
    usage: /<command>
  GiveLand:
    description: Gives a player more land
    usage: /<command> [Player] [Int]
  SetLand:
    description: Sets a players land
    usage: /<command> [Player] [Int]
  GetLand:
    description: Gets a players land
    usage: /<command> [Player]
  Stuck:
    description: Teleports a player out of a protection
    usage: /<command>